#%RAML 1.0 NamedExample
AccountNoID-example:

value:
- lastName: "sharma"
  creationDate: 2018-01-01T09:00:00Z
  address: "kolar road bhopal"
  type:  personal
  country: "india"
  miles: 227
  postal: "50049"
  firstName: "Vibhor"
